name: Deploy to Development

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
      domain: whitepinedev.jpkramer.com
      web_port: '3001'
      api_port: '4001'
      mongodb_uri_env: MONGODB_URI_DEV
      pm2_processes: web-dev,api-dev
    secrets: inherit
