name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      domain: whitepine.jpkramer.com
      web_port: '3000'
      api_port: '4000'
      mongodb_uri_env: MONGODB_URI_PROD
      pm2_processes: web-prod,api-prod
    secrets: inherit
